CREATE DATABASE IF NOT EXISTS SETGAME;

USE DATABASE SETGAME;

CREATE TABLE IF NOT EXISTS USER (
	ID INT NOT NULL AUTO_INCREMENT,
	NAME CHAR(20) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SCORE (
	ID INT NOT NULL AUTO_INCREMENT,
	USER INT NOT NULL,
	SCORE INT NOT NULL,
	ELAPSED_TIME INT NOT NULL,
	PRIMARY KEY (ID)
);



